CREATE TABLE "GCG_6889_SHIP_IN_PLACE" (
 "PackingList" CHAR(7),
 "CustID" CHAR(6),
 "SO" CHAR(7),
 "SOSuffix" CHAR(4),
 "SOLine" CHAR(4),
 "Part" CHAR(20),
 "Location" CHAR(2),
 "Lot" CHAR(15),
 "Bin" CHAR(6),
 "Heat" CHAR(15),
 "SerialNumber" CHAR(30),
 "Qty" NUMERIC(15,6),
 "Shipped" BIT NOT NULL,
 "ShipToID" CHAR(6),
 "CountQty" NUMERIC(15,6),
 "CycleDate" DATE,
 "Notes" CHAR(1000),
 "DateTimePlaced" DATETIME,
 "UserPlaced" CHAR(8),
 "ProgramPlaced" CHAR(8),
 "DateTimeShipped" DATETIME,
 "UserShipped" CHAR(8),
 "ProgramShipped" CHAR(8) );