CREATE TABLE "GCG_6889_SHIPID" (
 "PackingList" CHAR(7),
 "SO" CHAR(7),
 "SOSuffix" CHAR(4),
 "SOLine" CHAR(4),
 "Part" CHAR(20),
 "Location" CHAR(2),
 "Lot" CHAR(15),
 "Heat" CHAR(15),
 "SerialNumber" CHAR(30),
 "ShipToID" CHAR(6),
 "NewShipToID" CHAR(6),
 "DateTimeChanged" DATETIME,
 "UserChanged" CHAR(8),
 "ProgramChanged" CHAR(8) );
